import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/cart_item.dart';
import '../models/product.dart';
import '../models/order.dart';
import '../services/database_service.dart';
import '../utils/constants.dart';

class CartProvider with ChangeNotifier {
  final Map<String, CartItem> _items = {};
  final DatabaseService _dbService = DatabaseService();
  bool _isLoading = false;

  CartProvider() {
    _loadCart();
  }

  Map<String, CartItem> get items => {..._items};
  bool get isLoading => _isLoading;

  int get itemCount => _items.values.fold(0, (sum, item) => sum + item.quantity);

  double get totalAmount => _items.values.fold(0.0, (sum, item) => sum + item.totalPrice);

  // Load from local storage
  Future<void> _loadCart() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final cartJson = prefs.getString(AppConstants.prefsCartKey);
      if (cartJson != null) {
        final List<dynamic> decoded = jsonDecode(cartJson);
        for (var item in decoded) {
          final cartItem = CartItem.fromMap(item as Map<String, dynamic>);
          _items[cartItem.product.id] = cartItem;
        }
        notifyListeners();
      }
    } catch (_) {}
  }

  // Save to local storage
  Future<void> _saveCart() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final encoded = _items.values.map((item) => item.toMap()).toList();
      await prefs.setString(AppConstants.prefsCartKey, jsonEncode(encoded));
    } catch (_) {}
  }

  // Add Item to Cart
  void addItem(Product product) {
    if (_items.containsKey(product.id)) {
      // increase quantity
      _items.update(
        product.id,
        (existing) => CartItem(
          product: existing.product,
          quantity: existing.quantity + 1,
        ),
      );
    } else {
      _items[product.id] = CartItem(product: product, quantity: 1);
    }
    _saveCart();
    notifyListeners();
  }

  // Decrease quantity / remove
  void decreaseItem(String productId) {
    if (!_items.containsKey(productId)) return;
    if (_items[productId]!.quantity > 1) {
      _items.update(
        productId,
        (existing) => CartItem(
          product: existing.product,
          quantity: existing.quantity - 1,
        ),
      );
    } else {
      _items.remove(productId);
    }
    _saveCart();
    notifyListeners();
  }

  // Remove completely
  void removeItem(String productId) {
    _items.remove(productId);
    _saveCart();
    notifyListeners();
  }

  // Clear Cart
  void clear() {
    _items.clear();
    _saveCart();
    notifyListeners();
  }

  // Checkout and submit order
  Future<bool> checkout({required String userId, required String shippingAddress}) async {
    if (_items.isEmpty) return false;
    _isLoading = true;
    notifyListeners();

    try {
      final order = OrderModel(
        id: '', // Generated by DatabaseService
        userId: userId,
        items: _items.values.toList(),
        totalAmount: totalAmount,
        shippingAddress: shippingAddress,
        status: 'Pending',
        createdAt: DateTime.now(),
      );

      await _dbService.createOrder(order);
      clear();
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (_) {
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }
}
